steps:
  # Step 1: Fetch Firestore service account key from Secret Manager
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud secrets versions access latest --secret=firestore-service-account-key --project=leetsummarizer > /workspace/firestore-service-account-key.json

  # Step 2: Ensure the directory exists in the GCS bucket
  - name: 'gcr.io/cloud-builders/gsutil'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Check if the directory exists
        if gsutil ls gs://airflow-dags-leetsummarizer/dags/src/data_preprocessing/; then
          echo "Directory exists."
        else
          # Create the directory if it doesn't exist
          gsutil mb -p leetsummarizer gs://airflow-dags-leetsummarizer/dags/src/data_preprocessing
          echo "Directory created."
        fi

  # Step 3: Move Firestore service account key to the desired location
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', '/workspace/firestore-service-account-key.json', 'gs://airflow-dags-leetsummarizer/dags/src/data_preprocessing/service_account_key.json']

  - name: 'gcr.io/cloud-builders/gsutil'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gsutil -m rsync -r --exclude 'logs/scheduler/latest' . gs://airflow-dags-leetsummarizer


logsBucket: 'gs://airflow-dag-logs/'
timeout: '180s'
