steps:
  # Step to retrieve the service account key from Secret Manager
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud secrets versions access latest --secret=firestore-service-account-key > /workspace/service_account_key.json

  # Step to copy the service account key to the appropriate location in the repository
  - name: 'ubuntu'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        mkdir -p dags/src/data_preprocessing
        mv /workspace/service_account_key.json dags/src/data_preprocessing/service_account_key.json

  # Step to sync the DAGs folder with the GCS bucket
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['rsync', '-r', '.', 'gs://airflow-dags-leetsummarizer/dags']
    dir: 'dags' 

logsBucket: 'gs://airflow-dag-logs/'
timeout: '120s'
