steps:
  # Step 1: Clone the repository
  - name: 'gcr.io/cloud-builders/git'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        git clone https://github.com/deepanshgandhi/LeetSummarizer.git

  # Step 2: Copy files to the GCS bucket
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gsutil -m cp -r LeetSummarizer/* gs://airflow-dags-leetsummarizer/
  
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Retrieving service account key from Secret Manager..."
        gcloud secrets versions access latest --secret=firestore-service-account-key > /workspace/service_account_key.json
        echo "Service account key retrieved and saved to /workspace/service_account_key.json"

  - name: 'ubuntu'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Creating necessary directories..."
        mkdir -p dags/src/data_preprocessing
        echo "Moving service account key to dags/src/data_preprocessing..."
        mv /workspace/service_account_key.json dags/src/data_preprocessing/service_account_key.json
        echo "Service account key moved to dags/src/data_preprocessing/service_account_key.json"
        echo "Listing contents of dags/src/data_preprocessing:"
        ls -l dags/src/data_preprocessing

logsBucket: 'gs://airflow-dag-logs/'
timeout: '300s'