steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud secrets versions access latest --secret=firestore-service-account-key > /workspace/service_account_key.json

  - name: 'ubuntu'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        mkdir -p dags/src/data_preprocessing
        mv /workspace/service_account_key.json dags/src/data_preprocessing/service_account_key.json
        ls -l dags/src/data_preprocessing

  - name: 'gcr.io/cloud-builders/gsutil'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gsutil -m cp -r . gs://airflow-dags-leetsummarizer/
        gsutil ls -r gs://airflow-dags-leetsummarizer/

logsBucket: 'gs://airflow-dag-logs/'
timeout: '120s'