# Dockerfile

FROM pytorch/pytorch:2.3.0-cuda12.1-cudnn8-runtime

WORKDIR /app

RUN apt-get update
RUN apt-get install -y curl git software-properties-common

# Install requirements
COPY requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt

# Copy the FastAPI application
COPY main.py /app/main.py

# Ensure the directory for logs exists and has the correct permissions
RUN mkdir -p /app/logs
RUN chmod -R 777 /app/logs

# Set environment variables to store logs in the correct location
ENV LOG_FILE=/app/logs/app.log

# Expose the port
EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]