name: Sync to GCP

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        version: 'latest'
        project_id: leetsummarizer
        service_account_key: ${{ secrets.GCP_SA_KEY }}
    
    - name: Sync to GCS
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
      run: |
        echo "${{ secrets.GCP_SA_KEY }}" > key.json
        gcloud auth activate-service-account --key-file=key.json
        gsutil -m rsync -r ./ gs://airflow-dags-leetsummarizer
