name: Sync to GCP

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        version: 'latest'
        project_id: leetsummarizer
        service_account_key: ${{ secrets.GCP_SA_KEY }}
    
    - name: Sync to GCS
      run: |
        gsutil -m rsync -r ./ gs://airflow-dags-leetsummarizer
