# name: Build and Push Image Docker

# on:
#   push:
#    branches: [ main ]
#   pull_request:
#     branches: [ main ]
      
# jobs:
#   build:

#     runs-on: ubuntu-latest

#     steps:
#     - uses: actions/checkout@v1
    
#     - name: Docker Login
#       env:
#         DOCKER_USER: brijesh1012  
#         DOCKER_PASSWORD: dckr_pat_CeHjyuLji7TKHNpVTxXKfKzgkJQ
#       run: |
#         docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

        
#     - name: Build and Push Image
#       run: |
#         docker image build -t brijesh1012/hello-docker-hub:latest .
#         docker push brijesh1012/hello-docker-hub:latest
